### ISSUE TITLE
How to import keycloak-scripts.json?

### ISSUE THREAD

**Issue by fabiofalci** [thomasdarimont/embedded-spring-boot-keycloak-server#13]
Hello,

I'm trying to import a META-INF/keycloak-scripts.json using this embedded server and it's not working.

After some trying, I was able to import using keycloak official docker images.

I'm imagining the issue is that this project doesn't use WildFly and looks like this import is done by WildFly? (ScriptProviderDeploymentProcessor/KeycloakProviderDeploymentProcessor)

**Comment by thomasdarimont** [comment]
@fabiofalci thanks for the pointer!

I added support for script based keycloak components in the latest master. Could you give it a spin?

**Comment by fabiofalci** [comment]
Nice! It works fine now, thanks.

The only issue I had was when you don't have a keycloak-script.json it throws an exception and stops the server.

```
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: argument "src" is null
	at com.github.thomasdarimont.keycloak.embedded.support.SpringBootPlatform$Delegate.exit(SpringBootPlatform.java:66) ~[embedded-keycloak-server-spring-boot-support-0.21361-20200515.091024-1.jar:0.21361-SNAPSHOT]
	at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:127) ~[keycloak-services-9.0.3.jar:9.0.3]
	at com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication.<init>(EmbeddedKeycloakApplication.java:28) ~[embedded-keycloak-server-spring-boot-support-0.21361-20200515.091024-1.jar:0.21361-SNAPSHOT]
```

Shouldn't this be handled?

**Comment by thomasdarimont** [comment]
@fabiofalci thanks for the hint... Yes this should be handled. It's fixed in master now
