### ISSUE TITLE
Could not find keycloak import file

### ISSUE THREAD

**Issue by sjacek** [thomasdarimont/embedded-spring-boot-keycloak-server#17]
I see a message in the log file:
`2020-05-20 08:34:43.581  INFO 4056 --- [           main] c.g.t.k.e.EmbeddedKeycloakApplication    : Could not find keycloak import file ServletContext resource [/keycloak-realm-config.json]`

The realm file is declared in application.yml of embedded-keycloak-server-plain module.  But there is no such a file in sources.

**Comment by thomasdarimont** [comment]
This is optional and only serves for demonstration purposes. You can specify a file via the `keycloak.custom.migration.importLocation` property to import an existing realm. 

I could add it to the -custom example module though.

**Comment by rjeeb** [comment]
@thomasdarimont is there any example of how specifying realms directory to be imported?

I add the realm directory under the resources and specifying the properties as follows:
```yaml
    migration:
      importProvider: dir
      importLocation: realms
``` 
but yet the directory is not found as it tries to find it under this base path
`/tmp/undertow-docbase.3416615456268389963.8080/realms`

**Comment by SessevmezBugra** [comment]
I have put keycloak-realm-config.json in META-INF but i still get error Could not find keycloak import file ServletContext resource [/META-INF//keycloak-realm-config.json]

**Comment by tubbynl** [comment]
i've specified it as classpath resource and put t in `src/main/resources`

```properties
keycloak.custom.migration.import-location=classpath:/keycloak-realm-config.json
```

and check if the `resources` block in the maven pom build section (if present) includes json files

**Comment by AlexTMjugador** [comment]
Putting a realm JSON file in the classpath doesn't even work for me:

```
java.io.FileNotFoundException: class path resource [keycloak-realm-config.json] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/C:/Users/user/restmock/target/restmock-undertow-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/keycloak-realm-config.json
        at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-5.3.9.jar!/:5.3.9]
        at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:154) ~[spring-core-5.3.9.jar!/:5.3.9]
        at com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication.tryImportRealm(EmbeddedKeycloakApplication.java:102) ~[embedded-keycloak-server-spring-boot-support-5.0.2.jar!/:5.0.2]
```

I think this is caused due to the following code, which treats the resource as if it was a file on the filesystem:

https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server/blob/fc9c610f27b784dc76300a622f0b2840264ec5f3/embedded-keycloak-server-spring-boot-support/src/main/java/com/github/thomasdarimont/keycloak/embedded/EmbeddedKeycloakApplication.java#L100-L114

It'd be nice to let Keycloak read the file from an input stream and not depend on concrete details on how it is stored.

**Comment by AlexTMjugador** [comment]
In my case setting `import-location` to `file:keycloak-realm-config.json` worked. The JSON file was read from the current working directory (i.e. where I ran `java -jar`). It looks like Spring Boot interprets resources that do not start with that prefix as web resources. I'm using the latest version of this project at the time of writing, 5.0.2.

Interestingly, when I launched my application during Spring integration tests, the classpath resource approach worked. I think that's because in that case the classpath is composed of actual files in the filesystem, and are not yet in an archive.

It also looks like the Keycloak implementations of the `ImportProvider` interface don't really support classpath resources. For example, the single file import provider requires a `File` for construction. It also doesn't look like there is a supported and documented way to register your own provider with Keycloak.
