### ISSUE TITLE
Plain application fails to start when built with Jetty profile

### ISSUE THREAD

**Issue by nigredo-tori** [thomasdarimont/embedded-spring-boot-keycloak-server#28]
I build the project with the `jetty` profile, and run the resulting `plain` JAR:
```sh
$ mvn -P jetty clean install -DskipTests
$ java -jar ./embedded-keycloak-server-plain/target/embedded-keycloak-server-plain-jetty-2.4.0-SNAPSHOT.jar
```
The server fails to start, producing [this log](https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server/files/5089862/keycloak-log.txt). AFAICT, this is the important part:
```
Caused by: javax.naming.NameNotFoundException: spring is not bound
  at org.eclipse.jetty.jndi.local.localContextRoot.getContext(localContextRoot.java:177) ~[jetty-jndi-9.4.29.v20200521.jar!/:9.4.29.v20200521]
  at org.eclipse.jetty.jndi.local.localContextRoot.lookup(localContextRoot.java:370) ~[jetty-jndi-9.4.29.v20200521.jar!/:9.4.29.v20200521]
  at org.eclipse.jetty.jndi.local.localContextRoot.lookup(localContextRoot.java:379) ~[jetty-jndi-9.4.29.v20200521.jar!/:9.4.29.v20200521]
  at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409) ~[na:na]
  at org.springframework.jndi.JndiTemplate.lambda$lookup$0(JndiTemplate.java:157) ~[spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
  at org.springframework.jndi.JndiTemplate.execute(JndiTemplate.java:92) ~[spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
  at org.springframework.jndi.JndiTemplate.lookup(JndiTemplate.java:157) ~[spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
  at org.springframework.jndi.JndiTemplate.lookup(JndiTemplate.java:179) ~[spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
  at com.github.thomasdarimont.keycloak.embedded.support.InfinispanCacheManagerProvider.getCacheManager(InfinispanCacheManagerProvider.java:18) ~[embedded-keycloak-server-spring-boot-support-2.4.0-SNAPSHOT.jar!/:2.4.0-SNAPSHOT]
  ... 59 common frames omitted
```
However, I have too little experience with Spring and JNDI to figure out who should have bound `spring`, and why that didn't happen.

**Comment by nigredo-tori** [comment]
This seems to be caused by https://github.com/spring-projects/spring-boot/issues/22241. Upgrading Spring Boot helps.

**Comment by thomasdarimont** [comment]
Could you try this again with the latest master or the latest release 2.4.0?

**Comment by nigredo-tori** [comment]
The server starts OK with 2.4.0.
