### ISSUE TITLE
Error on upgrade to 5.0.2

### ISSUE THREAD

**Issue by ebremer** [thomasdarimont/embedded-spring-boot-keycloak-server#58]
I've upgraded from 4.0.0 to 5.0.2, past upgrades went smooth but in this upgrade, whether with prior version's database or none for a new one, I am getting the following error:

```
2021-10-28 13:05:20.568  WARN 368 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2021-10-28 13:05:20.585  INFO 368 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2021-10-28 13:05:20.585  INFO 368 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1752 ms
2021-10-28 13:05:20.732  INFO 368 --- [           main] c.g.t.k.embedded.EmbeddedKeycloakConfig  : Could not find profile.properties on classpath.
2021-10-28 13:05:21.158  INFO 368 --- [           main] c.g.t.k.embedded.EmbeddedKeycloakConfig  : Using infinispan configuration from jar:file:/C:/Users/erich/.m2/repository/com/github/thomasdarimont/embedded-spring-boot-keycloak-server/embedded-keycloak-server-spring-boot-support/5.0.2/embedded-keycloak-server-spring-boot-support-5.0.2.jar!/infinispan.xml
2021-10-28 13:05:21.725  WARN 368 --- [           main] org.infinispan.PERSISTENCE               : ISPN000554: jboss-marshalling is deprecated and planned for removal
2021-10-28 13:05:21.744  INFO 368 --- [           main] org.infinispan.CONTAINER                 : ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2021-10-28 13:05:21.804  INFO 368 --- [           main] org.infinispan.CONTAINER                 : ISPN000128: Infinispan version: Infinispan 'Taedonggang' 12.1.7.Final
2021-10-28 13:05:21.905  INFO 368 --- [           main] org.infinispan.CLUSTER                   : ISPN000078: Starting JGroups channel ISPN with stack jgroups
2021-10-28 13:05:24.606  INFO 368 --- [           main] org.jgroups.protocols.pbcast.GMS         : Corsair-60971: no members discovered after 2014 ms: creating cluster as coordinator
2021-10-28 13:05:24.612  INFO 368 --- [           main] org.infinispan.CLUSTER                   : ISPN000094: Received new cluster view for channel ISPN: [Corsair-60971|0] (1) [Corsair-60971]
2021-10-28 13:05:24.616  INFO 368 --- [           main] org.infinispan.CLUSTER                   : ISPN000079: Channel ISPN local address is Corsair-60971, physical addresses are [192.168.158.1:63518]
2021-10-28 13:05:25.038  INFO 368 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2021-10-28 13:05:25.190  INFO 368 --- [           main] org.jboss.resteasy.resteasy_jaxrs.i18n   : RESTEASY002225: Deploying javax.ws.rs.core.Application: class com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication
2021-10-28 13:05:25.191  INFO 368 --- [           main] org.jboss.resteasy.resteasy_jaxrs.i18n   : RESTEASY002205: Adding provider class org.keycloak.services.error.KeycloakErrorHandler from Application class com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication
2021-10-28 13:05:25.192  INFO 368 --- [           main] org.jboss.resteasy.resteasy_jaxrs.i18n   : RESTEASY002200: Adding class resource org.keycloak.services.resources.ThemeResource from Application class com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication
2021-10-28 13:05:25.192  INFO 368 --- [           main] org.jboss.resteasy.resteasy_jaxrs.i18n   : RESTEASY002200: Adding class resource org.keycloak.services.resources.JsResource from Application class com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication
2021-10-28 13:05:25.192  INFO 368 --- [           main] org.jboss.resteasy.resteasy_jaxrs.i18n   : RESTEASY002205: Adding provider class org.keycloak.services.filters.KeycloakSecurityHeadersFilter from Application class com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication
2021-10-28 13:05:25.192  INFO 368 --- [           main] org.jboss.resteasy.resteasy_jaxrs.i18n   : RESTEASY002220: Adding singleton resource org.keycloak.services.resources.RealmsResource from Application class com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication
2021-10-28 13:05:25.193  INFO 368 --- [           main] org.jboss.resteasy.resteasy_jaxrs.i18n   : RESTEASY002210: Adding provider singleton org.keycloak.services.util.ObjectMapperResolver from Application class com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication
2021-10-28 13:05:25.193  INFO 368 --- [           main] org.jboss.resteasy.resteasy_jaxrs.i18n   : RESTEASY002220: Adding singleton resource org.keycloak.services.resources.admin.AdminRoot from Application class com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication
2021-10-28 13:05:25.193  INFO 368 --- [           main] org.jboss.resteasy.resteasy_jaxrs.i18n   : RESTEASY002220: Adding singleton resource org.keycloak.services.resources.WelcomeResource from Application class com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication
2021-10-28 13:05:25.193  INFO 368 --- [           main] org.jboss.resteasy.resteasy_jaxrs.i18n   : RESTEASY002220: Adding singleton resource org.keycloak.services.resources.RobotsResource from Application class com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication
2021-10-28 13:05:25.411  INFO 368 --- [           main] org.apache.wicket.Application            : [wicketFilter] init: Wicket core library initializer
2021-10-28 13:05:25.412  INFO 368 --- [           main] org.apache.wicket.Application            : [wicketFilter] init: Wicket extensions initializer
2021-10-28 13:05:25.482  INFO 368 --- [           main] o.a.wicket.protocol.http.WebApplication  : [wicketFilter] Started Wicket version 9.4.0 in DEPLOYMENT mode
2021-10-28 13:05:25.484  INFO 368 --- [           main] io.undertow                              : starting server: Undertow - 2.2.10.Final
2021-10-28 13:05:25.499  INFO 368 --- [           main] org.xnio                                 : XNIO version 3.8.4.Final
2021-10-28 13:05:25.506  INFO 368 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.4.Final
2021-10-28 13:05:25.553  INFO 368 --- [           main] org.jboss.threads                        : JBoss Threads version 2.3.3.Final
2021-10-28 13:05:25.598  INFO 368 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 8080 (http)
2021-10-28 13:05:25.689  INFO 368 --- [           main] o.k.url.DefaultHostnameProviderFactory   : Frontend: <request>, Admin: <frontend>, Backend: <request>
2021-10-28 13:05:26.037  INFO 368 --- [           main] faultInfinispanConnectionProviderFactory : Node name: Corsair-60971, Site name: null
2021-10-28 13:05:26.065 ERROR 368 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IncompatibleClassChangeError: Method 'liquibase.servicelocator.ServiceLocator liquibase.servicelocator.ServiceLocator.getInstance()' must be InterfaceMethodref constant
	at org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider.baseLiquibaseInitialization(DefaultLiquibaseConnectionProvider.java:84) ~[keycloak-model-jpa-15.0.2.jar:15.0.2]
	at org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider.create(DefaultLiquibaseConnectionProvider.java:75) ~[keycloak-model-jpa-15.0.2.jar:15.0.2]
	at org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider.create(DefaultLiquibaseConnectionProvider.java:57) ~[keycloak-model-jpa-15.0.2.jar:15.0.2]
	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316) ~[keycloak-services-15.0.2.jar:15.0.2]
	at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lazyInit(LiquibaseDBLockProvider.java:62) ~[keycloak-model-jpa-15.0.2.jar:15.0.2]
	at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$waitForLock$2(LiquibaseDBLockProvider.java:96) ~[keycloak-model-jpa-15.0.2.jar:15.0.2]
	at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:758) ~[keycloak-server-spi-private-15.0.2.jar:15.0.2]
	at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.waitForLock(LiquibaseDBLockProvider.java:94) ~[keycloak-model-jpa-15.0.2.jar:15.0.2]
	at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:134) ~[keycloak-services-15.0.2.jar:15.0.2]
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:250) ~[keycloak-server-spi-private-15.0.2.jar:15.0.2]
	at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:128) ~[keycloak-services-15.0.2.jar:15.0.2]
	at com.github.thomasdarimont.keycloak.embedded.support.SpringBootPlatformProvider.startup(SpringBootPlatformProvider.java:72) ~[embedded-keycloak-server-spring-boot-support-5.0.2.jar:5.0.2]
	at com.github.thomasdarimont.keycloak.embedded.support.SpringBootPlatformProvider.onApplicationEvent(SpringBootPlatformProvider.java:28) ~[embedded-keycloak-server-spring-boot-support-5.0.2.jar:5.0.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79) ~[spring-boot-2.5.4.jar:2.5.4]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:353) ~[spring-boot-2.5.4.jar:2.5.4]

2021-10-28 13:05:26.069  INFO 368 --- [           main] io.undertow                              : stopping server: Undertow - 2.2.10.Final
2021-10-28 13:05:26.077  INFO 368 --- [           main] org.apache.wicket.Application            : [wicketFilter] destroy: Wicket core library initializer
2021-10-28 13:05:26.078  INFO 368 --- [           main] org.apache.wicket.Application            : [wicketFilter] destroy: Wicket extensions initializer
2021-10-28 13:05:26.090  INFO 368 --- [           main] o.i.manager.DefaultCacheManager          : Stopping cache manager null on Corsair-60971
2021-10-28 13:05:26.102  INFO 368 --- [           main] org.infinispan.CLUSTER                   : ISPN000080: Disconnecting JGroups channel ISPN
```

**Comment by janroesler** [comment]
I have a similar error with a newly set up 5.0.2. I do not know if the errors are related.
`
o.s.boot.SpringApplication: Application run failed
liquibase.exception.ServiceNotFoundException: Could not find unique implementation of liquibase.executor.Executor.  Found 0 implementations
`
On startup in production mode.

**Comment by hannybNdq** [comment]
@ebremer did you resolve this? I'm having the same issue

**Comment by ebremer** [comment]
Yes.  I will be looking into it again soon.   - Erich

**Comment by ebremer** [comment]
I was able to jump to 7.0.2 successfully.
