### ISSUE TITLE
Could not find unique implementation of liquibase.executor.Executor.  Found 0 implementations

### ISSUE THREAD

**Issue by Sithira** [thomasdarimont/embedded-spring-boot-keycloak-server#67]
Has anyone encountered this error before? 

It works when I run it from IntelliJ but not when I try to run it from docker. The same result while trying to run the jar file manually from the command line.

Any help would be greatly appreciated. Thanks ♥️

```java 
liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.ServiceNotFoundException: liquibase.exception.ServiceNotFoundException: Could not find unique implementation of liquibase.executor.Executor.  Found 0 implementations
        at liquibase.change.ChangeFactory.register(ChangeFactory.java:87) ~[liquibase-core-3.6.3.jar!/:na]
        at org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider.baseLiquibaseInitialization(DefaultLiquibaseConnectionProvider.java:128) ~[keycloak-model-jpa-15.0.2.jar!/:15.0.2]
        at org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider.create(DefaultLiquibaseConnectionProvider.java:75) ~[keycloak-model-jpa-15.0.2.jar!/:15.0.2]
        at org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider.create(DefaultLiquibaseConnectionProvider.java:57) ~[keycloak-model-jpa-15.0.2.jar!/:15.0.2]
        at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316) ~[keycloak-services-15.0.2.jar!/:15.0.2]
        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lazyInit(LiquibaseDBLockProvider.java:62) ~[keycloak-model-jpa-15.0.2.jar!/:15.0.2]
        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$waitForLock$2(LiquibaseDBLockProvider.java:96) ~[keycloak-model-jpa-15.0.2.jar!/:15.0.2]
        at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:758) ~[keycloak-server-spi-private-15.0.2.jar!/:15.0.2]
        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.waitForLock(LiquibaseDBLockProvider.java:94) ~[keycloak-model-jpa-15.0.2.jar!/:15.0.2]
        at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:134) ~[keycloak-services-15.0.2.jar!/:15.0.2]
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:250) ~[keycloak-server-spi-private-15.0.2.jar!/:15.0.2]
        at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:128) ~[keycloak-services-15.0.2.jar!/:15.0.2]
        at com.github.thomasdarimont.keycloak.embedded.support.SpringBootPlatformProvider.startup(SpringBootPlatformProvider.java:72) ~[embedded-keycloak-server-spring-boot-support-5.0.2.jar!/:5.0.2]
        at com.github.thomasdarimont.keycloak.embedded.support.SpringBootPlatformProvider.onApplicationEvent(SpringBootPlatformProvider.java:28) ~[embedded-keycloak-server-spring-boot-support-5.0.2.jar!/:5.0.2]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.9.jar!/:5.3.9]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.9.jar!/:5.3.9]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.9.jar!/:5.3.9]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.9.jar!/:5.3.9]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.9.jar!/:5.3.9]
        at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:353) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.4.jar!/:2.5.4]
        at com.ninexlabs.mlmpro.authservice.AuthServerApplication.main(AuthServerApplication.java:14) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[auth-service.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[auth-service.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[auth-service.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[auth-service.jar:na]
Caused by: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.ServiceNotFoundException: liquibase.exception.ServiceNotFoundException: Could not find unique implementation of liquibase.executor.Executor.  Found 0 implementations
        at liquibase.change.AbstractChange.createChangeMetaData(AbstractChange.java:98) ~[liquibase-core-3.6.3.jar!/:na]
        at liquibase.change.ChangeFactory.getChangeMetaData(ChangeFactory.java:101) ~[liquibase-core-3.6.3.jar!/:na]
        at liquibase.change.ChangeFactory.register(ChangeFactory.java:71) ~[liquibase-core-3.6.3.jar!/:na]
        ... 36 common frames omitted
Caused by: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.ServiceNotFoundException: liquibase.exception.ServiceNotFoundException: Could not find unique implementation of liquibase.executor.Executor.  Found 0 implementations
        at liquibase.change.AbstractChange.createChangeParameterMetadata(AbstractChange.java:151) ~[liquibase-core-3.6.3.jar!/:na]
        at liquibase.change.AbstractChange.createChangeMetaData(AbstractChange.java:84) ~[liquibase-core-3.6.3.jar!/:na]
        ... 38 common frames omitted
Caused by: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.ServiceNotFoundException: liquibase.exception.ServiceNotFoundException: Could not find unique implementation of liquibase.executor.Executor.  Found 0 implementations
        at liquibase.executor.ExecutorService.getExecutor(ExecutorService.java:30) ~[liquibase-core-3.6.3.jar!/:na]
        at org.keycloak.connections.jpa.updater.liquibase.custom.CustomCreateIndexChange.generateStatements(CustomCreateIndexChange.java:60) ~[keycloak-model-jpa-15.0.2.jar!/:15.0.2]
        at liquibase.change.AbstractChange.supports(AbstractChange.java:334) ~[liquibase-core-3.6.3.jar!/:na]
        at liquibase.change.ChangeParameterMetaData.analyzeSupportedDatabases(ChangeParameterMetaData.java:105) ~[liquibase-core-3.6.3.jar!/:na]
        at liquibase.change.ChangeParameterMetaData.<init>(ChangeParameterMetaData.java:87) ~[liquibase-core-3.6.3.jar!/:na]
        at liquibase.change.AbstractChange.createChangeParameterMetadata(AbstractChange.java:148) ~[liquibase-core-3.6.3.jar!/:na]
        ... 39 common frames omitted
Caused by: liquibase.exception.ServiceNotFoundException: liquibase.exception.ServiceNotFoundException: Could not find unique implementation of liquibase.executor.Executor.  Found 0 implementations
        at liquibase.servicelocator.ServiceLocator.newInstance(ServiceLocator.java:216) ~[liquibase-core-3.6.3.jar!/:na]
        at liquibase.executor.ExecutorService.getExecutor(ExecutorService.java:26) ~[liquibase-core-3.6.3.jar!/:na]
        ... 44 common frames omitted
Caused by: liquibase.exception.ServiceNotFoundException: Could not find unique implementation of liquibase.executor.Executor.  Found 0 implementations
        at liquibase.servicelocator.ServiceLocator.findClass(ServiceLocator.java:188) ~[liquibase-core-3.6.3.jar!/:na]
        at liquibase.servicelocator.ServiceLocator.newInstance(ServiceLocator.java:214) ~[liquibase-core-3.6.3.jar!/:na]
        ... 45 common frames omitted
```

**Comment by Sithira** [comment]
I resolved it.

in my gradle file i had this for all my spring-boot services.

```java
bootJar {
    launchScript()
}
```

This was a class loading issue so, removing that line if you have it will resolve your problem.
