### ISSUE TITLE
java.nio.file.NoSuchFileException: myproject-0.0.0.jar!\BOOT-INF\lib\keycloak-model-jpa-18.0.0.jar

### ISSUE THREAD

**Issue by ebremer** [thomasdarimont/embedded-spring-boot-keycloak-server#73]
I'm using a shaded jar which contains my project plus the embedded keycloak server.  For the several past versions (embedded keycloak), I get the following error on startup logging of the uberjar, but all works, but I thought it would be good to figure out what is going on here.
```
java.nio.file.NoSuchFileException: D:\projects\myproject\target\myproject-0.0.0.jar!\BOOT-INF\lib\keycloak-model-jpa-18.0.0.jar
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[na:na]
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[na:na]
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[na:na]
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[na:na]
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[na:na]
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199) ~[na:na]
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851) ~[na:na]
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264) ~[na:na]
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[na:na]
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[na:na]
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[na:na]
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:347) ~[na:na]
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:318) ~[na:na]
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:257) ~[na:na]
        at org.hibernate.boot.archive.internal.JarFileBasedArchiveDescriptor.resolveJarFileReference(JarFileBasedArchiveDescriptor.java:168) ~[hibernate-core-5.6.9.Final.jar!/:5.6.9.Final]
        at org.hibernate.boot.archive.internal.JarFileBasedArchiveDescriptor.visitArchive(JarFileBasedArchiveDescriptor.java:51) ~[hibernate-core-5.6.9.Final.jar!/:5.6.9.Final]
        at org.hibernate.boot.archive.scan.spi.AbstractScannerImpl.scan(AbstractScannerImpl.java:48) ~[hibernate-core-5.6.9.Final.jar!/:5.6.9.Final]
        at org.hibernate.boot.model.process.internal.ScanningCoordinator.coordinateScan(ScanningCoordinator.java:76) ~[hibernate-core-5.6.9.Final.jar!/:5.6.9.Final]
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.prepare(MetadataBuildingProcess.java:107) ~[hibernate-core-5.6.9.Final.jar!/:5.6.9.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:269) ~[hibernate-core-5.6.9.Final.jar!/:5.6.9.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:189) ~[hibernate-core-5.6.9.Final.jar!/:5.6.9.Final]
        at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:75) ~[hibernate-core-5.6.9.Final.jar!/:5.6.9.Final]
        at org.keycloak.connections.jpa.util.JpaUtils.createEntityManagerFactory(JpaUtils.java:72) ~[keycloak-model-jpa-18.0.0.jar!/:18.0.0]
        at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.lambda$lazyInit$0(DefaultJpaConnectionProviderFactory.java:240) ~[keycloak-model-jpa-18.0.0.jar!/:18.0.0]
        at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:756) ~[keycloak-server-spi-private-18.0.0.jar!/:18.0.0]
        at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.lazyInit(DefaultJpaConnectionProviderFactory.java:163) ~[keycloak-model-jpa-18.0.0.jar!/:18.0.0]
        at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:88) ~[keycloak-model-jpa-18.0.0.jar!/:18.0.0]
        at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:66) ~[keycloak-model-jpa-18.0.0.jar!/:18.0.0]
        at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316) ~[keycloak-services-18.0.0.jar!/:18.0.0]
        at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:64) ~[keycloak-model-jpa-18.0.0.jar!/:18.0.0]
        at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:40) ~[keycloak-model-jpa-18.0.0.jar!/:18.0.0]
        at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316) ~[keycloak-services-18.0.0.jar!/:18.0.0]
        at org.keycloak.services.DefaultKeycloakSession.realmLocalStorage(DefaultKeycloakSession.java:228) ~[keycloak-services-18.0.0.jar!/:18.0.0]
        at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmDelegate(RealmCacheSession.java:149) ~[keycloak-model-infinispan-18.0.0.jar!/:18.0.0]
        at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmByName(RealmCacheSession.java:450) ~[keycloak-model-infinispan-18.0.0.jar!/:18.0.0]
        at org.keycloak.services.managers.ApplianceBootstrap.isNewInstall(ApplianceBootstrap.java:46) ~[keycloak-services-18.0.0.jar!/:18.0.0]
        at org.keycloak.services.resources.KeycloakApplication$3.run(KeycloakApplication.java:197) ~[keycloak-services-18.0.0.jar!/:18.0.0]
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:242) ~[keycloak-server-spi-private-18.0.0.jar!/:18.0.0]
        at org.keycloak.services.resources.KeycloakApplication.bootstrap(KeycloakApplication.java:174) ~[keycloak-services-18.0.0.jar!/:18.0.0]
        at com.github.thomasdarimont.keycloak.embedded.EmbeddedKeycloakApplication.bootstrap(EmbeddedKeycloakApplication.java:35) ~[embedded-keycloak-server-spring-boot-support-7.0.2.jar!/:7.0.2]
```
Note*** keycloak-model-jpa-18.0.0.jar is IN the jar file.

**Comment by ebremer** [comment]
I noticed a 12.x version of infinispan was being used so I forced it to 13.0.8.Final.  The error has gone away now.
